name: twinly
description: "Twinly - virtual fitting room app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  # Navigation & Icons
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2

  # State Management
  flutter_riverpod: ^3.4.3

  # 3D Avatar Rendering Engine (Person B)
  model_viewer_plus: ^1.7.0

  # Firebase
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0

  # RevenueCat — required for Shipaton submission
  purchases_flutter: ^10.11.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Asset Directories for 3D Models
  assets:
    - assets/models/