// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2xI20esnUHAHC9fUFiK6ARMwJBUMFEo',
    appId: '1:500892366854:web:9e3bb628ea85d9fbe76b87',
    messagingSenderId: '500892366854',
    projectId: 'twinly-cf976',
    authDomain: 'twinly-cf976.firebaseapp.com',
    storageBucket: 'twinly-cf976.firebasestorage.app',
    measurementId: 'G-PX8N54Q6TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxbr52jT2dQQDXQWMDX2XUvOsAzhM8hAw',
    appId: '1:500892366854:android:862f58578374c624e76b87',
    messagingSenderId: '500892366854',
    projectId: 'twinly-cf976',
    storageBucket: 'twinly-cf976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9EU6Q5kXQH-JfgspoFk2RF0ULW2ZHHZ0',
    appId: '1:500892366854:ios:6b4ebfa646068042e76b87',
    messagingSenderId: '500892366854',
    projectId: 'twinly-cf976',
    storageBucket: 'twinly-cf976.firebasestorage.app',
    iosBundleId: 'com.example.fitStyleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9EU6Q5kXQH-JfgspoFk2RF0ULW2ZHHZ0',
    appId: '1:500892366854:ios:6b4ebfa646068042e76b87',
    messagingSenderId: '500892366854',
    projectId: 'twinly-cf976',
    storageBucket: 'twinly-cf976.firebasestorage.app',
    iosBundleId: 'com.example.fitStyleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr2xI20esnUHAHC9fUFiK6ARMwJBUMFEo',
    appId: '1:500892366854:web:10fba3b905b1f3cde76b87',
    messagingSenderId: '500892366854',
    projectId: 'twinly-cf976',
    authDomain: 'twinly-cf976.firebaseapp.com',
    storageBucket: 'twinly-cf976.firebasestorage.app',
    measurementId: 'G-MB4TLG93T6',
  );
}
